DROP DATABASE IF EXISTS linkwatts;
CREATE DATABASE linkwatts;
USE linkwatts;
CREATE TABLE login(
	Cod_Log SMALLINT AUTO_INCREMENT NOT NULL,
	NomeUsu_Log VARCHAR(50) NOT NULL,
	Senha_Log VARCHAR(50) NOT NULL,
	Nome_Log VARCHAR(50) NOT NULL,
	Email_Log VARCHAR(50) NOT NULL,
	Sexo_Log VARCHAR(15) NOT NULL,
	CPF_Log VARCHAR(16) NOT NULL,
	DataNas_Log VARCHAR(16) NOT NULL,	
	CONSTRAINT Cod_Log PRIMARY KEY(Cod_Log));
INSERT INTO login(NomeUsu_Log, Senha_Log) VALUES ('admin', 'admin');
CREATE TABLE cadastroele(
	Cod_Ele SMALLINT AUTO_INCREMENT NOT NULL,
	Valor_Ele DOUBLE NOT NULL,
	Watts_Ele DOUBLE NOT NULL,
	Mes_Ele VARCHAR(50) NOT NULL,
	Npes_Ele INT NOT NULL,
	wPes_Ele DOUBLE NOT NULL,
	valorPes_Ele DOUBLE NOT NULL,
	CONSTRAINT Cod_Ele PRIMARY KEY(Cod_Ele));
CREATE TABLE cadastroagua(
	Cod_Agua SMALLINT AUTO_INCREMENT NOT NULL,
	Valor_Agua DOUBLE NOT NULL,
	Mes_Agua VARCHAR(50) NOT NULL,
	Npes_Agua INT NOT NULL,
	Nmetros_Agua DOUBLE NOT NULL,
	valorPes_Agua DOUBLE NOT NULL,
	CONSTRAINT Cod_Agua PRIMARY KEY(Cod_Agua));